export const direccion = [
    {
        Provincia:'San Jose',
        Canton:'Montes de Oca',
        Distrito:'San Pedro',
        Direccion:'De la entrada principal de la UCR 100 metros al este',
        CodigoPostal:'11501',
        telefono:'88888888',
        UsuarioID:1,
    },
    {
        Provincia:'Alajuela',
        Canton:'Alajuela',
        Distrito:'San Rafael',
        Direccion:'De la entrada principal de la UCR 100 metros al este',
        CodigoPostal:'11501',
        telefono:'88888888',
        UsuarioID:2,
    },
    {
        Provincia:'Cartago',
        Canton:'Cartago',
        Distrito:'Oriental',
        Direccion:'De la municipalidad de Cartago 100 metros al este',
        CodigoPostal:'11501',
        telefono:'88888888',
        UsuarioID:3,
    },
    {
        Provincia: "Heredia",
        Canton: "Heredia",
        Distrito: "San Francisco",
        Direccion: "De la municipalidad de Heredia 100 metros al este",
        CodigoPostal: "11501",
        telefono: "88888888",
        UsuarioID: 4,
      },
      {
        Provincia: "Guanacaste",
        Canton: "Liberia",
        Distrito: "Cañas Dulces",
        Direccion: "De la municipalidad de Liberia 100 metros al este",
        CodigoPostal: "11501",
        telefono: "88888888",
        UsuarioID: 5,
      },
      {
        Provincia: "Puntarenas",
        Canton: "Puntarenas",
        Distrito: "Chacarita",
        Direccion: "De la municipalidad de Puntarenas 100 metros al este",
        CodigoPostal: "11501",
        telefono: "88888888",
        UsuarioID: 6,
      },
    ]
