export const producto = [
  {
    Nombre: "Camisa Nike COLB Supreme",
    Precio: 20000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 1,
    UsuarioID:2,
  },
  {
    Nombre: "Pantalon Supreme",
    Precio: 30000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 2,
    UsuarioID:2,
  },
  {
    Nombre: "Tenis Nike Air Max",
    Precio: 40000,
    Cantidad: 10,
    Estado: false,
    CategoriaID: 3,
    UsuarioID:2,
  },
  {
    Nombre: "Sweter Supreme",
    Precio: 50000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 4,
    UsuarioID:2,
  },
  {
    Nombre: "Camiseta Jordan",
    Precio: 60000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 1,
    UsuarioID:3,
  },
  {
    Nombre: "Pantalon Jordan",
    Precio: 70000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 2,
    UsuarioID:3,
  },
  {
    Nombre: "Tenis Jordan",
    Precio: 80000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 3,
    UsuarioID:3,   
  },
  {
    Nombre: "Sweter Jordan",
    Precio: 90000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 4,
    UsuarioID:3,
  },
  {
    Nombre: "Camiseta Adidas",
    Precio: 100000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 1,
    UsuarioID:6,
  },
  {
    Nombre: "Pantalon Adidas",
    Precio: 110000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 2,
    UsuarioID:6,
  },
  {
    Nombre: "Tenis Adidas",
    Precio: 120000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 3,
    UsuarioID:6,
  },
  {
    Nombre: "Sweter Adidas",
    Precio: 130000,
    Cantidad: 10,
    Estado: true,
    CategoriaID: 4,
    UsuarioID:6,
  },
];
